### PR TITLE
Milestone2

### PR DESCRIPTION
**Pull request by pountzas**
# Milestone 2. 
We added three new responsive sections.

- Categories
- Latest News
- Latest Deals

### using flexbox, grid and float

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [x] [MANDATORY]   Your `Latest News` section doesn't match with the original on screen 768px.
         -  Yours
             ln_fc
         -  Original
             ln_org
  - [x] [MANDATORY]   This section doesn't match with the original on screen 768px.
         -  Yours
            hf_fc
         -  Original
            hf_org
   - [x] [MANDATORY]   Your `Latest Deals` section doesn't match with the original on screen 768px.
         -  Yours
            ld_fc
         -  Original
             ld_org






  

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric*

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :balloon: 

Hi @pountzas and @Amalcxc, great job on this project :+1: However, most of the sections in the project have not been implemented as in the requirements :slightly_smiling_face: Aside from the header and the footer, all the other sections needs to be fixed in order to align properly as in the original. The following screenshot will seek to help us fix the issue at hand when the app is in tablet mode (min-width: 768px)
`Original`
bbn1
`Clone`
bbn
`Original`
lnn1
`Clone`
lnn
`Original`
lf1
`Clone`
lf
`Original`
hf
`Clone`
hf1
`Original`
lnn1
`Clone`
lnn

Before submitting another code review request, kindly visit this [link](https://perma.cc/M5ZV-Q2D6), press (CTRL + SHIFT + I) to change the browser to different screen sizes. Check if the clone project is exactly the layout as in the original.

Once this is done, kindly request another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by addod19** [comment]
> # Status:  CHANGES REQUIRED 
> _Great job guys so far clap 100 +1. However, there are few issues we need to address before we move on, please check the comments below._
> 
> * ### To Highlight
>   
>   * [x]  The project is clean. 100
>   * [x]  The project follows Git flow. 100
> * ### To Improve
>   
>   * [x]  [MANDATORY]   Your `Latest News` section doesn't match with the original on screen 768px.
>     -  Yours
>     ln_fc
>     -  Original
>     ln_org
>   * [x]  [MANDATORY]   This section doesn't match with the original on screen 768px.
>     -  Yours
>     hf_fc
>     -  Original
>     hf_org
>   * [x]  [MANDATORY]   Your `Latest Deals` section doesn't match with the original on screen 768px.
>     -  Yours
>     ld_fc
>     -  Original
>     ld_org
> 
> _Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric rocket . I wish you all the very best 1st_place_medal_
> 
> ### _Keep working hard._
> ### _Happy Codingsmiley_
> *_Regards, [Rukundo Eric](https://rukundo-eric.herokuapp.com/) , [LinkedIn](https://www.linkedin.com/in/rukundo-eric/), Slack: Rukundo Eric_

`768px`

**Comment by Amalcxc** [comment]
Original 768px
Screen Shot 2021-02-27 at 11 45 17 AM
clone
Screen Shot 2021-02-27 at 11 46 22 AM
Original
Screen Shot 2021-02-27 at 11 49 00 AM
clone
Screen Shot 2021-02-27 at 11 49 19 AM
Original 
Screen Shot 2021-02-27 at 11 49 39 AM
clone
Screen Shot 2021-02-27 at 11 49 49 AM
Original
Screen Shot 2021-02-27 at 11 50 03 AM
clone
Screen Shot 2021-02-27 at 11 50 15 AM

**Comment by pountzas** [comment]
Hello as you can see on the following pictures there is a problem on the original site media queries that transitions to tablet when the resolution is 769 and above. If you carefully see the pictures of the previous TSE you will see you ask us to do the opposite.

- ## Original 767px
resolution 767

- ## Original 768px
resolution 768

- ## Original 769px
resolution 769

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello guys :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
